name: Rust CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Slang
        run: |
          curl -L -o slang "https://github.com/xlsynth/slang-rs/releases/download/ci/slang"
          chmod +x slang

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: export SLANG_PATH=`realpath slang` && cargo test
